package com.example.DynamoDBApplication.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;

import lombok.Getter;
import lombok.Setter;

@DynamoDBDocument  //json format created by this annotation
@DynamoDBTable(tableName = "person")
@Getter
@Setter
public class Person {

    @DynamoDBHashKey(attributeName = "personId")
    @DynamoDBAutoGeneratedKey
    public String personId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute(attributeName = "address")
    @DynamoDBTypeConvertedJson
    private Address address;
}
